# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'phuong.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1255, 911)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 70, 901, 581))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.display = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.display.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.display.setObjectName("display")
        self.horizontalLayout.addWidget(self.display)
        self.hour = QtWidgets.QLCDNumber(self.centralwidget)
        self.hour.setGeometry(QtCore.QRect(20, 710, 251, 81))
        self.hour.setObjectName("hour")
        self.day = QtWidgets.QLCDNumber(self.centralwidget)
        self.day.setGeometry(QtCore.QRect(630, 710, 401, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.day.setFont(font)
        self.day.setSmallDecimalPoint(False)
        self.day.setDigitCount(19)
        self.day.setObjectName("day")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(60, 660, 171, 41))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser1 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser1.setGeometry(QtCore.QRect(640, 660, 391, 41))
        self.textBrowser1.setObjectName("textBrowser1")
        self.butto_camera = QtWidgets.QPushButton(self.centralwidget)
        self.butto_camera.setGeometry(QtCore.QRect(80, 0, 121, 41))
        self.butto_camera.setObjectName("butto_camera")
        self.button_video = QtWidgets.QPushButton(self.centralwidget)
        self.button_video.setGeometry(QtCore.QRect(280, 0, 121, 41))
        self.button_video.setObjectName("button_video")
        self.button_img = QtWidgets.QPushButton(self.centralwidget)
        self.button_img.setGeometry(QtCore.QRect(480, 0, 121, 41))
        self.button_img.setObjectName("button_img")
        self.capture = QtWidgets.QPushButton(self.centralwidget)
        self.capture.setGeometry(QtCore.QRect(690, 0, 121, 41))
        self.capture.setObjectName("capture")
        self.list_img = QtWidgets.QListView(self.centralwidget)
        self.list_img.setGeometry(QtCore.QRect(930, 200, 141, 441))
        self.list_img.setObjectName("list_img")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(940, 140, 131, 51))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.folder = QtWidgets.QTextBrowser(self.centralwidget)
        self.folder.setGeometry(QtCore.QRect(850, 0, 191, 41))
        self.folder.setObjectName("folder")
        self.name_folder = QtWidgets.QTextEdit(self.centralwidget)
        self.name_folder.setGeometry(QtCore.QRect(1070, 0, 151, 41))
        self.name_folder.setObjectName("name_folder")
        self.IMGNG = QtWidgets.QPushButton(self.centralwidget)
        self.IMGNG.setGeometry(QtCore.QRect(940, 70, 241, 51))
        self.IMGNG.setIconSize(QtCore.QSize(30, 30))
        self.IMGNG.setObjectName("IMGNG")
        self.capture_thuong = QtWidgets.QPushButton(self.centralwidget)
        self.capture_thuong.setGeometry(QtCore.QRect(410, 680, 171, 51))
        self.capture_thuong.setObjectName("capture_thuong")
        self.camer_thuong = QtWidgets.QPushButton(self.centralwidget)
        self.camer_thuong.setGeometry(QtCore.QRect(410, 750, 171, 41))
        self.camer_thuong.setObjectName("camer_thuong")
        self.list_img_camer_thuong = QtWidgets.QListView(self.centralwidget)
        self.list_img_camer_thuong.setGeometry(QtCore.QRect(1100, 200, 141, 441))
        self.list_img_camer_thuong.setObjectName("list_img_camer_thuong")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(1100, 140, 141, 51))
        self.textBrowser_4.setObjectName("textBrowser_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1255, 21))
        self.menubar.setObjectName("menubar")
        self.menumenu = QtWidgets.QMenu(self.menubar)
        self.menumenu.setObjectName("menumenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionfile_img = QtWidgets.QAction(MainWindow)
        self.actionfile_img.setObjectName("actionfile_img")
        self.actionfile_video = QtWidgets.QAction(MainWindow)
        self.actionfile_video.setObjectName("actionfile_video")
        self.menumenu.addAction(self.actionfile_img)
        self.menumenu.addAction(self.actionfile_video)
        self.menumenu.addSeparator()
        self.menubar.addAction(self.menumenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.display.setText(_translate("MainWindow", "display"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">giờ-phút-giây</span></p></body></html>"))
        self.textBrowser1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">ngày tháng năm-phương lại lập trình</span></p></body></html>"))
        self.butto_camera.setText(_translate("MainWindow", "camera yolov5"))
        self.button_video.setText(_translate("MainWindow", "video yolov5"))
        self.button_img.setText(_translate("MainWindow", "ảnh yolov5"))
        self.capture.setText(_translate("MainWindow", "chụp ảnh yolov5"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">list ảnh chụp từ camera yolov5</span></p></body></html>"))
        self.folder.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">folder chứa ảnh :</span></p></body></html>"))
        self.IMGNG.setText(_translate("MainWindow", "folder chứa ảnh NG (click to show img)"))
        self.capture_thuong.setText(_translate("MainWindow", "chụp ảnh thường_đưa vào detect"))
        self.camer_thuong.setText(_translate("MainWindow", "camera ko yolov5"))
        self.textBrowser_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">list ảnh detect từ camera thường</span></p></body></html>"))
        self.menumenu.setTitle(_translate("MainWindow", "menu"))
        self.actionfile_img.setText(_translate("MainWindow", "file_img"))
        self.actionfile_video.setText(_translate("MainWindow", "file video"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
